// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9-MKYcKWqHUSVcWrmEBRNMLdMNaovM-4',
    appId: '1:910531123888:android:72d53c3466de48e86bb975',
    messagingSenderId: '910531123888',
    projectId: 'bizconnect-5b495',
    storageBucket: 'bizconnect-5b495.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6mRMBWRUMu3zZ9X1lV-GHIoyk80LS1sI',
    appId: '1:910531123888:ios:e77d0a31ad1500706bb975',
    messagingSenderId: '910531123888',
    projectId: 'bizconnect-5b495',
    storageBucket: 'bizconnect-5b495.firebasestorage.app',
    iosBundleId: 'com.example.bizconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6mRMBWRUMu3zZ9X1lV-GHIoyk80LS1sI',
    appId: '1:910531123888:ios:e77d0a31ad1500706bb975',
    messagingSenderId: '910531123888',
    projectId: 'bizconnect-5b495',
    storageBucket: 'bizconnect-5b495.firebasestorage.app',
    iosBundleId: 'com.example.bizconnect',
  );
}
